"""
Django settings for MikoSocial project.

Generated by 'django-admin startproject' using Django 4.2.
Configured for: REST API, JWT Auth, WebSocket, PostgreSQL.
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# .env файлын жүктөө
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# SECURITY
# =============================================================================

SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-dev-key-change-in-production"
)

DEBUG = os.getenv("DEBUG", "True").lower() in ("true", "1", "yes")

allowed_env = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1,.onrender.com")
ALLOWED_HOSTS = [host.strip() for host in allowed_env.split(",") if host.strip()]


# =============================================================================
# INSTALLED APPS
# =============================================================================

INSTALLED_APPS = [
    # Django Channels ASGI сервер (daphne биринчи турушу керек)
    "daphne",

    # Django стандарттык тиркемелер
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Үчүнчү тараптын тиркемелери
    "rest_framework",               # Django REST Framework
    "rest_framework_simplejwt",      # JWT аутентификация
    "corsheaders",                   # CORS колдоо
    "channels",                      # WebSocket колдоо

    # MikoSocial тиркемелери
    "apps.accounts",
    "apps.posts",
    "apps.follows",
    "apps.chat",
    "apps.notifications",
]


# =============================================================================
# MIDDLEWARE
# =============================================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # CORS middleware — SessionMiddleware'ден мурун турушу керек
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =============================================================================
# URL CONFIGURATION
# =============================================================================

ROOT_URLCONF = "mikosocial.urls"


# =============================================================================
# TEMPLATES
# =============================================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# =============================================================================
# ASGI / WSGI
# =============================================================================

# ASGI — WebSocket + HTTP
ASGI_APPLICATION = "mikosocial.asgi.application"

# WSGI — HTTP гана (backup)
WSGI_APPLICATION = "mikosocial.wsgi.application"


# =============================================================================
# DATABASE (PostgreSQL)
# =============================================================================

import urllib.parse

database_url = os.getenv("DATABASE_URL")
if database_url:
    url = urllib.parse.urlparse(database_url)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": url.path[1:],
            "USER": url.username,
            "PASSWORD": url.password,
            "HOST": url.hostname,
            "PORT": url.port or 5432,
        }
    }
elif os.getenv("DB_ENGINE") == "postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "mikosocial"),
            "USER": os.getenv("DB_USER", "postgres"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }



# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# =============================================================================
# STATIC FILES
# =============================================================================

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# =============================================================================
# MEDIA FILES (User uploads: avatars, post images)
# =============================================================================

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# =============================================================================
# DEFAULT PRIMARY KEY
# =============================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =============================================================================
# DJANGO REST FRAMEWORK
# =============================================================================

REST_FRAMEWORK = {
    # Стандарт аутентификация — JWT
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # Стандарт permission — аутентификация талап кылынат
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    # Pagination — кийинчерээк pagination кошуу оңой
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    # Datetime форматы
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%SZ",
}


# =============================================================================
# JWT SETTINGS (Simple JWT)
# =============================================================================

SIMPLE_JWT = {
    # Access token — 15 мүнөт (кыска = коопсуз)
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", "15"))
    ),
    # Refresh token — 7 күн
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.getenv("JWT_REFRESH_TOKEN_LIFETIME_DAYS", "7"))
    ),
    # Refresh token бир жолу колдонулат (ротация)
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    # JWT header префикси
    "AUTH_HEADER_TYPES": ("Bearer",),
    # Token'дин ичиндеги маалымат
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}


# =============================================================================
# CORS SETTINGS
# =============================================================================

cors_env = os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://localhost:5173")
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_env.split(",") if origin.strip()]
CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "True").lower() in ("true", "1")

# Credentials (cookies, auth headers) жөнөтүүгө уруксат
CORS_ALLOW_CREDENTIALS = True


# =============================================================================
# DJANGO CHANNELS (WebSocket)
# =============================================================================

CHANNEL_LAYERS = {
    "default": {
        # Development үчүн InMemory, Production үчүн Redis
        "BACKEND": "channels.layers.InMemoryChannelLayer",
        # Production үчүн:
        # "BACKEND": "channels_redis.core.RedisChannelLayer",
        # "CONFIG": {
        #     "hosts": [os.getenv("REDIS_URL", "redis://localhost:6379/0")],
        # },
    }
}


# =============================================================================
# FILE UPLOAD SETTINGS
# =============================================================================

# Максималдуу файл өлчөмү — 5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
