# Generated by Django 6.0.7 on 2026-10-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to="chat/audio/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="chat/images/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(blank=True, default="", max_length=2000),
        ),
    ]
